# Generated by Django 5.0.6 on 2024-06-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_material_is_published_material_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='email',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='email'),
        ),
    ]
