# Generated by Django 5.0.6 on 2024-05-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='наименование категории'),
        ),
    ]
